### PR TITLE
Multiple Enhancements

### PR DESCRIPTION
**Pull request by InAnimaTe**
A while ago, I made some enhancements to this image and today, a few more. Figured Hacktoberfest would be a good time to actually contribute these back upstream for all to enjoy!

Changes:
- Utilize Python Slim base image - much smaller ;)
- Set zerobin as the entrypoint
- Create version variable to make tagging easier
- Cleanup readme

### CODE REVIEW

**Comment by InAnimaTe** [comment]
Hey @jcsaaddupuy just wanted to bump and see what your thoughts are on this PR! Would love to make this image better for everyone!

**Comment by jcsaaddupuy** [comment]
Hi! Sorry for the delay,

It seems pretty nice, i'll merge it à soon as possible ;)

Thanks for the PR!

**Comment by InAnimaTe** [comment]
Haha no problem! Thanks for the quick response!

**Comment by jcsaaddupuy** [comment]
I only updated the base image to use python 3.5.

Thanks !

**Pull request merged**
